GET http://localhost:8000/people

###

POST http://localhost:8000/people HTTP/1.1
Content-Type: application/json

{
    "firstName": "Joe",
    "lastName": "Biden"
}

###
GET http://localhost:8000/people/1

###
GET http://localhost:8000/people/search/findByLastName?name=Biden

###
PUT http://localhost:8000/people/1
Content-Type: application/json

{
    "firstName": "Joe",
    "lastName": "Putin"
}

###
PATCH http://localhost:8000/people/1
Content-Type: application/json

{
    "firstName": "Wang"
}

###
DELETE http://localhost:8000/people/1
